spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: user
    password: password
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE