spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/liquibase-master.xml
  banner:
    location: classpath:/banner.txt
  output:
    ansi:
      enabled: always